### ISSUE TITLE
Multiple kins for multivariate analysis?

### ISSUE THREAD

**Issue by TeaByrd** [hanchenphd/GMMAT#10]
Hey,

I'm fitting a glmmkin and getting this weird error:

 glmmkin("cbind(Campestanol.µg.dl,Campesterol.mg.dl,Sitosterol.mg.dl,Sitostanol.µg.dl,Stigmasterol.µg.dl) ~ MAPK.subgraph+ Calcium.dependent.signal.transduction + Matrix.metalloproteinase.subgraph + Synuclein.subgraph + Age + Sex",data = df,kins=as.matrix(K) ,id = "X",family = gaussian(link = "identity"),method.optim="AI")

Fitting a multiple phenotype analysis model...
 Show Traceback
Error in tau[covariance.idx[fixrho.idx & fixrho.idx0, 1]] <- sign(tau[covariance.idx[fixrho.idx & : NAs are not allowed in subscripted assignments

Fyi, there are no NA's in my input data.

Can you guys help me?

Thanks and best regards,
Thomas

**Comment by TeaByrd** [comment]
The full error traceback is:


Fitting a multiple phenotype analysis model...
Hide Traceback
Error in tau[covariance.idx[fixrho.idx & fixrho.idx0, 1]] <- sign(tau[covariance.idx[fixrho.idx & : NAs are not allowed in subscripted assignments
3.
glmmkin.multi.ai(fit0 = fit0, kins = kins, covariance.idx = covariance.idx, group.idx = group.idx, maxiter = maxiter, tol = tol, verbose = verbose)
2.
glmmkin.fit(fit0, kins, time.var, group.id, method = method, method.optim = method.optim, maxiter = maxiter, tol = tol, taumin = taumin, taumax = taumax, tauregion = tauregion, verbose = verbose)
1.
glmmkin("cbind(Campestanol.µg.dl,Campesterol.mg.dl,Sitosterol.mg.dl,Sitostanol.µg.dl,Stigmasterol.µg.dl) ~ MAPK.subgraph+ Calcium.dependent.signal.transduction + Matrix.metalloproteinase.subgraph + Synuclein.subgraph + Age + Sex", data = df, kins = as.matrix(K), id = "X", family = gaussian(link = "identity"), method.optim = "AI")

**Comment by hanchenphd** [comment]
Hi Thomas,

Thank you for your interest in GMMAT. Please send a reproducible (simulated) example to Han.Chen.2@uth.tmc.edu.

Best,
Han

**Comment by TeaByrd** [comment]
> Thank you for your interest in GMMAT. Please send a reproducible (simulated) example to [Han.Chen.2@uth.tmc.edu](mailto:Han.Chen.2@uth.tmc.edu).

Done.

**Comment by hanchenphd** [comment]
Hi Thomas,

Thanks for sending the example. It turns out the model failed to converge after 18 iterations. You can turn on verbose = TRUE and see the final results before the error message comes out.

Here is what I have from your simulated data:
Iteration  18 :
Variance component estimates:
 [1] 110.9965171   4.4361790  -0.8221718   8.0363526 103.9109311   4.6334911
 [7]  -1.3973041 112.0338919   1.4847256 114.8042512   5.6889635  -0.9337599
[13]   3.7117942   6.9516409  32.8185014   5.2663121  -2.1993178  12.8231543
[19]  10.4368199   8.4945722
Fixed-effect coefficients:
 [1]  3.636003e+01 -7.006902e+03  6.422148e+03  2.903393e+03 -2.069996e+00
 [6]  3.073065e+00  4.308775e+01  5.719090e+04  1.591060e+03 -5.677627e+04
[11] -9.931343e-01  1.213335e+00  3.940546e+01  3.613823e+04  5.288356e+03
[16] -3.907214e+04  7.940237e-01  2.231676e+00  3.760044e+01 -5.667807e+03
[21]  9.415645e+03 -1.933044e+03 -6.683720e-01  2.904007e+00

Note that the variance component estimates are used to construct two 4x4 covariance matrices (each with 10 parameters), and in your joint model with 4 phenotypes (in the Rmd file you sent to me) and 5 covariates will have 24 fixed-effects parameters (including 4 intercepts). Therefore, the total number of parameters in your model is 44, but your total sample size is only 106. Generally, I would not recommend fitting a model with the number of parameters > your sample size divided by 10, and in your case, you should try to fit a more parsimonious model with no greater than 10 parameters.

Some technical side notes: the glmmkin function checks variance and covariance estimates for each pair of phenotypes and ensures that the correlation is between -1 and 1, but this does not guarantee that the full covariance matrix is positive semi-definite. For example, the variance component estimates from iteration 18 above form two covariance matrices:

            [,1]       [,2]        [,3]       [,4]
[1,] 110.9965171   4.436179  -0.8221718   8.036353
[2,]   4.4361790 103.910931   4.6334911  -1.397304
[3,]  -0.8221718   4.633491 112.0338919   1.484726
[4,]   8.0363526  -1.397304   1.4847256 114.804251

and

           [,1]       [,2]      [,3]      [,4]
[1,]  5.6889635 -0.9337599  3.711794  6.951641
[2,] -0.9337599 32.8185014  5.266312 -2.199318
[3,]  3.7117942  5.2663121 12.823154 10.436820
[4,]  6.9516409 -2.1993178 10.436820  8.494572

The first matrix is a valid covariance matrix, but the second matrix is not positive semi-definite (the minimum eigenvalue is -2.148116), although all the pairwise correlations are between -1 and 1 (6.9516409 is the product of sqrt(5.6889635) and sqrt(8.494572), and 10.436820 is the product of sqrt(12.823154) and sqrt(8.494572): they are forced by the program to these values so that the pairwise correlations do not exceed 1). So this is likely a convergence issue with your data. Please try to use a more parsimonious model.

Best,
Han

**Comment by TeaByrd** [comment]
Thanks so much for that help, Han!

I know, my sample size is way too small, but I can't help it and have to work with it. Actually, the final model, that I want to build consists of 5 independent variables and ~ 40 dependent variables ... .

What do you exactly mean by "a more parsimonious model"? Can you maybe give me some examples?

Also another question: Would it help, if I reduce dimensionality and combine both dependent and independent variables (separately) by using a PCA? 

Thanks in advance,
best,
Thomas

**Comment by hanchenphd** [comment]
Hi Thomas,

Basically I was suggesting that you try simpler models with much fewer parameters (that's what "parsimony" means in statistics). For example, you can try to run these phenotypes separately, and then for each phenotype you will only have 2 variance component parameters (one for kinship, and one for residuals), instead of 30 variance-covariance parameters in a multi-phenotype model with 5 phenotypes. Or does it make sense to run these phenotypes in pairs (so that you have 6 variance-covariance parameters)?

Generally your sample size should be greater than 10 times the total number of parameters you are estimating in the model (variance-covariance parameters and fixed-effects parameters combined). It is a rule of thumb that I usually use. Although it does not guarantee convergence in model fitting, it is much less likely to observe convergence issues in simpler models with fewer parameters.

Best,
Han
