### ISSUE TITLE
Error reading bimfile

### ISSUE THREAD

**Issue by yuliu426** [hanchenphd/GMMAT#25]
Hello, 

Trying to use glmm.score to conduct score test, however, I always encounter this issue: Error reading bimfile
I am pretty sure the path and file name are correct. What could be the problem?

Thanks!

**Comment by hanchenphd** [comment]
Does your bimfile have a .bim suffix?

**Comment by yuliu426** [comment]
Thanks for your reply!
Yes, it does. But when specifying the `-outfile` I didn't include the prefix.

**Comment by hanchenphd** [comment]
Can you share your code for running glmm.score along with the error message?

**Comment by yuliu426** [comment]
```
R:  container='/mnt/mfs/statgen/containers/lmm.sif',expand='${ }', stderr = 'tmp/merged_plink_common.AA.stderr', stdout = 'tmp/merged_plink_common.AA.stdout'
    library('GMMAT')
    null_model = readRDS("tmp/merged_plink_common.AA.GMMAT.rds")
    glmm.score(null_model, 
               infile = "~/project/alzheimers-family/PCA_QC/20210507/merged_plink_common.AA", 
               outfile = "tmp/merged_plink_common.AA.AD_African.gmmat.score.txt", 
               MAF.range = c(0.001,1), 
               miss.cutoff = 0.01,
               nperbatch = 10)
```


`cat tmp/merged_plink_common.European.stdout`
Error reading bimfile: ~/project/alzheimers-family/PCA_QC/20210507/merged_plink_common.AA.bim


Thanks!

**Comment by hanchenphd** [comment]
I have not seen this error message before. Here are my suggestions:

1. Please check if merged_plink_common.AA.bim exists in the directory you specified, and see if the file is readable (e.g., use head, tail, or less).
2. See if you can run this locally in an interactive session, instead of using the container.
3. If you are deploying this job to a computing cluster or a cloud platform, please make sure that the infiles are accessible from the computing node.
