### ISSUE TITLE
Use of GMMAT GLMM approach for predictive modelling

### ISSUE THREAD

**Issue by JonChan0** [hanchenphd/GMMAT#58]
Hi,

Big fan of your work on building GMMAT as a rare variant association analysis package.
I am considering using a logistic mixed model approach for prediction of case/control status. How might you suggest I approach this and is there a suitable implementation in GMMAT?

Thanks,
Jonathan

**Comment by hanchenphd** [comment]
Hi Jonathan,

Thank you for your interest in GMMAT! I am sorry that currently there are no suitable functions for predictive modeling in GMMAT, but please feel free to modify the `glmmkin` function to compute/output measures that you need.

Best,
Han

**Comment by JonChan0** [comment]
Hi Han,

Thanks for the reply. My thought process at the moment is to use glmmkin to train a subset of UKB with response variable of case/control status and predictors of x genetic variants, covariates and random effect (with GRM * variance component to define its variance).

If I want to predict on test subset, I understand using the fixed-effects coefficients from the output of glmmkin but am unsure about how to implement the random effects for the test samples. Should I derive the GRM within the test samples and multiply with the variance component estimate trained from glmmkin? How might one approach this from an implementation perspective?

Also are the random effects implemented, random-intercepts and/or random-slopes effects?

Thanks so much for your help,
Jonathan

**Comment by hanchenphd** [comment]
Hi Jonathan,

I am not sure if it is meaningful to "transfer" the random effects from your training set to the testing set. It largely depends on how the samples were selected. For example, if you purposefully select unrelated individuals into the testing set, then the random effects would disappear. If you keep related individuals in both your training and testing sets, you would also want to ensure that these two sets are completely independent (i.e. no relatives between the two sets). If you work with the UKB data, I would recommend using their sparse kinship matrix, instead of the GRM, because the latter is an N x N dense matrix and would take a lot of memory. Sorry I don't have much experience with risk prediction and cannot provide more constructive comments.

If you provide a kinship matrix or a GRM, by default `glmmkin` will fit a model with a random intercept. You have the option of adding a random slope on top of that.

Best,
Han
